Исправление алгоритма transform-win
logistictech/adbkit-logcat pull request #1
Opened 2016-10-15 07:00 UTC by licht741

2016-10-17 11:00 UTC, alexander-khovansky requested changes

2016-10-17 11:00 UTC, alexander-khovansky commented on src/logcat/transform-win.coffee
> +      chunk = Buffer.concat([@savedR, chunk])
Синтаксически это верно, но в Coffee обычно (и в этом проекте) принят стиль без скобок:

    Buffer.concat [@savedR, chunk]

2016-10-17 11:00 UTC, alexander-khovansky commented on src/logcat/transform-win.coffee
> +            lo = hi + 1
Лишний фрагмент, можно просто выйти из цикла (break)

2016-10-17 11:00 UTC, alexander-khovansky commented on src/logcat/transform-win.coffee
> +            lo = hi + 1
Фрагмент начиная с if - лишний, можно просто выйти из цикла (break)

2016-10-17 11:00 UTC, alexander-khovansky commented on src/logcat/transform-win.coffee
>          count_elems_to_last = last - hi
Лишняя переменная. Без нее код и короче и выразительнее

2016-10-17 11:00 UTC, alexander-khovansky commented on src/logcat/transform-win.coffee
> +            @savedR = chunk.slice hi, last + 1
Если второй аргумент равен концу буфера, его можно (и нужно для выразительности) опускать, как сделано в предыдущем блоке

2016-10-17 11:00 UTC, alexander-khovansky commented on src/logcat/transform-win.coffee
>            if hi isnt lo
Больше в стиле Coffee идиома `unless hi is lo`, как ниже.
(Я знаю, что это я так написал.)

2016-10-17 13:06 UTC, licht741 commented on src/logcat/transform-win.coffee
> +            lo = hi + 1
fix

2016-10-17 13:07 UTC, nnezhevskii commented on src/logcat/transform-win.coffee
> +            @savedR = chunk.slice hi, last + 1
fix

2016-10-17 13:09 UTC, licht741 commented on src/logcat/transform-win.coffee
> +            lo = hi + 1
fix

2016-10-17 13:10 UTC, licht741 commented on src/logcat/transform-win.coffee
>          count_elems_to_last = last - hi
fix

2016-10-17 13:10 UTC, licht741 commented on src/logcat/transform-win.coffee
> +      chunk = Buffer.concat([@savedR, chunk])
fix

2016-10-17 13:12 UTC, nnezhevskii commented on src/logcat/transform-win.coffee
>            if hi isnt lo
fix

2016-10-17 13:30 UTC, alexander-khovansky requested changes

2016-10-17 13:30 UTC, alexander-khovansky commented on src/logcat/transform-win.coffee
> +        else if last is hi + 1
Лучше читается когда однотипные условия организованы единообразно (одинаковый порядок операндов):

    hi is last
    hi is last - 1  или  hi + 1 is last

2016-10-17 13:30 UTC, alexander-khovansky commented on src/logcat/transform-win.coffee
>            if chunk[hi + 1] is 0x0d
Выразительнее (еще и эффективнее) `chunk[last]`

2016-10-17 13:30 UTC, alexander-khovansky commented on src/logcat/transform-win.coffee
> +            break
Теперь эти две строчки дублируются - можно объединить блоки

2016-10-18 04:43 UTC, licht741 commented on src/logcat/transform-win.coffee
> +        else if last is hi + 1
fix

2016-10-18 04:47 UTC, licht741 commented on src/logcat/transform-win.coffee
> +            break
fix

2016-10-18 04:47 UTC, licht741 commented on src/logcat/transform-win.coffee
>            if chunk[hi + 1] is 0x0d
fi

2016-10-18 14:53 UTC, alexander-khovansky approved these changes

2016-10-18 14:54 UTC, merged